print('This is a test of multiplying an input number by 50')
inputNumber = input('Please input a number and I will then multiply it by 50: ')
print('Your number provided is ' + inputNumber)
inputNumber = int(inputNumber)
print('Your number multiplied is: ')
print (inputNumber * 50)
y = input("Provide another number you would like for me to multiply your original number by: ")
y = int(y)
print (inputNumber * y)