import numbers
print('Here I will demonstrate some basic math')
number = 40 ** 40
print('40 to the 40th power is:' , number)
print('Now it is time to make things a bit more complex')
print('Please enter your first name')
firstName = input()
print('Please enter your last name')
lastName = input()
print('According to your input, your name is ' + firstName + ' ' + lastName)
print('Here we will use the len functionality to show the length of your name')
print('The length of your first name is')
print(len(firstName))
print('The length of your last name is')
print(len(lastName))
print('It is nice to meet you, ' + firstName)
print('We will now proceed to some other fun things that Python can do')
print('Next, ' + firstName + ', please provide your age')
userAge = input()
print('Thank you. You appear to be ' + userAge + ' years old')
print('You will be ' + str(int(userAge) + 1) + ' in a year.')
print('In 50 years, you will be ' + str(int(userAge) + 50))